FROM python:3.12-alpine

RUN apk add --no-cache bash git subversion

COPY pyproject.toml README.md /package/
COPY src /package/src
RUN pip install --no-cache-dir /package pytest

WORKDIR /workspace
ENV PYTHONPATH=/workspace/src
