name: Publish PureDarwin 17.4 toolbox

on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_toolbox-publish.yml
    with:
      toolbox: docker:builder/compiler/puredarwin/17.4/x86_64
